# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170224_1451'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='User',
        ),
    ]
